name: Quality Gates

on:
  push:
    branches:
      - deploy

jobs:
  standard-checks:
    name: Quality gates
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lighthouse benchmarks
        run: npm run ci:lighthouse

